"""Request/response schemas, split per workstream (docs/PHASE2_ARCHITECTURE_AUDIT.md, "Enabler — done").

Every name the single-module ``jev_api.schemas`` exported is re-exported here, so
``from jev_api.schemas import X`` keeps working. Integrator-owned: a workstream defines its schemas in
its own module (events.py, governance.py, experiments.py, security.py, ...) and appends ONE import line
below plus its names to ``__all__``. Shared envelopes (error body, pagination) stay integrator-only.
"""

from __future__ import annotations

from jev_api.schemas import events, experiments, governance, security  # noqa: F401 - WS placeholders
from jev_api.schemas.audit import (
    AuditEntryOut,
    AuditPage,
)
from jev_api.schemas.base import (
    ORM,
    DbId,
)
from jev_api.schemas.intel import (
    DecisionBatchList,
    DecisionFeedbackCounts,
    DomainKey,
    EvaluationRunList,
    EvaluationRunOut,
    EvidenceOwner,
    FeedbackTarget,
    HistoryEntity,
    HistoryPoint,
    IntelDecisionList,
    IntelDecisionOut,
    IntelEvidenceOut,
    IntelEvidencePage,
    IntelFeedbackIn,
    IntelFeedbackList,
    IntelFeedbackOut,
    IntelHistory,
    IntelPage,
    IntelRunList,
    IntelRunOut,
    IntelWarningList,
    IntelWarningOut,
    RunTrigger,
    SavedScenarioList,
    SavedScenarioOut,
    ScenarioRequest,
    ScenarioSpecIn,
    Severity,
    Verdict,
    WarningEventOut,
    WarningStatus,
    WarningUpdate,
)
from jev_api.schemas.me import (
    MeFeedbackIn,
    MeFeedbackOut,
    MeScenarioRequest,
    MeScenarioSpec,
)
from jev_api.schemas.model_registry import (
    ExperimentDetail,
    ExperimentOut,
    MetricOut,
    ModelVersionDetail,
    ModelVersionOut,
)
from jev_api.schemas.movies import (
    FavoriteRequest,
    InteractionResult,
    MovieBrief,
    MovieCreate,
    MovieDetail,
    MoviePage,
    RateRequest,
)
from jev_api.schemas.recs import (
    FeedbackOut,
    FeedbackRequest,
    RecIntelligence,
    RecommendationHistoryItem,
    RecommendationItem,
    RecommendationResponse,
    SignalValue,
    SimpleRecItem,
    SimpleRecResponse,
)
from jev_api.schemas.users import (
    LoginRequest,
    OnboardingRequest,
    PreferenceUpdate,
    RegisterRequest,
    TokenResponse,
    UserOut,
)

__all__ = [
    "ORM",
    "AuditEntryOut",
    "AuditPage",
    "DbId",
    "DecisionBatchList",
    "DecisionFeedbackCounts",
    "DomainKey",
    "EvaluationRunList",
    "EvaluationRunOut",
    "EvidenceOwner",
    "ExperimentDetail",
    "ExperimentOut",
    "FavoriteRequest",
    "FeedbackOut",
    "FeedbackRequest",
    "FeedbackTarget",
    "HistoryEntity",
    "HistoryPoint",
    "IntelDecisionList",
    "IntelDecisionOut",
    "IntelEvidenceOut",
    "IntelEvidencePage",
    "IntelFeedbackIn",
    "IntelFeedbackList",
    "IntelFeedbackOut",
    "IntelHistory",
    "IntelPage",
    "IntelRunList",
    "IntelRunOut",
    "IntelWarningList",
    "IntelWarningOut",
    "InteractionResult",
    "LoginRequest",
    "MeFeedbackIn",
    "MeFeedbackOut",
    "MeScenarioRequest",
    "MeScenarioSpec",
    "MetricOut",
    "ModelVersionDetail",
    "ModelVersionOut",
    "MovieBrief",
    "MovieCreate",
    "MovieDetail",
    "MoviePage",
    "OnboardingRequest",
    "PreferenceUpdate",
    "RateRequest",
    "RecIntelligence",
    "RecommendationHistoryItem",
    "RecommendationItem",
    "RecommendationResponse",
    "RegisterRequest",
    "RunTrigger",
    "SavedScenarioList",
    "SavedScenarioOut",
    "ScenarioRequest",
    "ScenarioSpecIn",
    "Severity",
    "SignalValue",
    "SimpleRecItem",
    "SimpleRecResponse",
    "TokenResponse",
    "UserOut",
    "Verdict",
    "WarningEventOut",
    "WarningStatus",
    "WarningUpdate",
]
