"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-23 14:40:52.360848
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("dataset_version", sa.String(length=120), nullable=False),
        sa.Column("training_config", sa.JSON(), nullable=False),
        sa.Column("training_seed", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("artifact_path", sa.String(length=500), nullable=False),
        sa.Column("artifact_bytes", sa.Integer(), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    with op.batch_alter_table("model_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_versions_is_active"), ["is_active"], unique=False)

    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("runtime_min", sa.Integer(), nullable=True),
        sa.Column("directors", sa.JSON(), nullable=False),
        sa.Column("cast", sa.JSON(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("countries", sa.JSON(), nullable=False),
        sa.Column("imdb_id", sa.String(length=16), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("n_ratings", sa.Integer(), nullable=False),
        sa.Column("mean_rating", sa.Float(), nullable=True),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movies_n_ratings"), ["n_ratings"], unique=False)
        batch_op.create_index(batch_op.f("ix_movies_year"), ["year"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("recommendation_prefs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "experiments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=120), nullable=False),
        sa.Column("experiment_name", sa.String(length=120), nullable=False),
        sa.Column("dataset_version", sa.String(length=120), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("training_seed", sa.Integer(), nullable=False),
        sa.Column("split", sa.JSON(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_experiments_experiment_name"), ["experiment_name"], unique=False)

    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "movie_id", name="uq_favorite_user_movie"),
    )
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_favorites_user_id"), ["user_id"], unique=False)

    op.create_table(
        "movie_genres",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("movie_id", "genre_id"),
    )
    with op.batch_alter_table("movie_genres", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movie_genres_genre_id"), ["genre_id"], unique=False)

    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rating >= 0.5 AND rating <= 5.0", name="ck_rating_range"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "movie_id", name="uq_rating_user_movie"),
    )
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ratings_movie_id"), ["movie_id"], unique=False)
        batch_op.create_index("ix_ratings_user_updated", ["user_id", "updated_at"], unique=False)

    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("context", sa.String(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("reason_code", sa.String(length=32), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index("ix_rec_request", ["request_id"], unique=False)
        batch_op.create_index("ix_rec_user_created", ["user_id", "created_at"], unique=False)

    op.create_table(
        "user_genre_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "genre_id"),
    )
    op.create_table(
        "watch_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("watched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watch_history", schema=None) as batch_op:
        batch_op.create_index("ix_watch_time", ["watched_at"], unique=False)
        batch_op.create_index("ix_watch_user_time", ["user_id", "watched_at"], unique=False)

    op.create_table(
        "evaluation_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=32), nullable=False),
        sa.Column("protocol", sa.String(length=16), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("k", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_id", "model_name", "protocol", "metric", "k", name="uq_metric"),
    )
    with op.batch_alter_table("evaluation_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evaluation_metrics_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "recommendation_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("recommendation_id", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "feedback IN ('like','dislike','not_interested','clicked')", name="ck_feedback_kind"
        ),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation_feedback", schema=None) as batch_op:
        batch_op.create_index("ix_feedback_user_created", ["user_id", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recommendation_feedback_recommendation_id"), ["recommendation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendation_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_feedback_recommendation_id"))
        batch_op.drop_index("ix_feedback_user_created")

    op.drop_table("recommendation_feedback")
    with op.batch_alter_table("evaluation_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluation_metrics_experiment_id"))

    op.drop_table("evaluation_metrics")
    with op.batch_alter_table("watch_history", schema=None) as batch_op:
        batch_op.drop_index("ix_watch_user_time")
        batch_op.drop_index("ix_watch_time")

    op.drop_table("watch_history")
    op.drop_table("user_genre_preferences")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index("ix_rec_user_created")
        batch_op.drop_index("ix_rec_request")

    op.drop_table("recommendations")
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.drop_index("ix_ratings_user_updated")
        batch_op.drop_index(batch_op.f("ix_ratings_movie_id"))

    op.drop_table("ratings")
    with op.batch_alter_table("movie_genres", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movie_genres_genre_id"))

    op.drop_table("movie_genres")
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorites_user_id"))

    op.drop_table("favorites")
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiments_experiment_name"))

    op.drop_table("experiments")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movies_year"))
        batch_op.drop_index(batch_op.f("ix_movies_n_ratings"))

    op.drop_table("movies")
    with op.batch_alter_table("model_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_versions_is_active"))

    op.drop_table("model_versions")
    op.drop_table("genres")
    # ### end Alembic commands ###
